simulation:
  dt: 0.01
  T: 5.0
  solver: fixed

blocks:
  step:
    value_before: [[0.]]
    value_after: [[8.0]]
    start_time: .4

  error:
    num_inputs: 2
    signs: [1., -1.]

  pid:
    controller: PI
    Kp: [[0.5]]
    Ki: [[0.8]]

  sofa:
    scene_file: /home/aalessan/Documents/Perso/code/pySimBlocks/examples/generate/sofa/Finger.py
    input_keys: ["cable"]
    output_keys: ["tip", "measure"]

logging:
  - step.outputs.out
  - sofa.outputs.measure
  - pid.outputs.u

plots:
  - title: Ref vs Output
    signals:
      - step.outputs.out
      - sofa.outputs.measure
  - title: Command
    signals:
      - pid.outputs.u
