simulation:
  dt: 0.01
  solver: fixed
  T: 2.0
blocks:
  ref:
    value_before: [[0.0]]
    value_after: [[1.0]]
    start_time: 0.5
  plant:
    A: [[0.9]]
    B: [[1.0]]
    C: [[1.0]]
    x0: [[0.0]]
logging:
- ref.outputs.out
- plant.outputs.y
plots:
- title: Open Chain
  signals:
  - ref.outputs.out
  - plant.outputs.y
