simulation:
  dt: 0.01
  solver: fixed
  T: 3.0
blocks:
  ref:
    value_before: [[0.0]]
    value_after: [[1.0]]
    start_time: 0.5
  sum:
    signs: ++
  A:
    gain: [[0.9]]
    multiplication: Matrix (K @ u)
  B:
    gain: [[1.0]]
    multiplication: Matrix (K @ u)
  delay:
    num_delays: 1
    initial_output: [[0.0]]
  plant:
    A: [[0.9]]
    B: [[1.0]]
    C: [[1.0]]
    x0: [[0.0]]
logging:
- ref.outputs.out
- plant.outputs.x
- delay.outputs.out
plots:
- title: System response
  signals:
  - delay.outputs.out
  - plant.outputs.x
  - ref.outputs.out
