simulation:
  dt: 1/60
  T: 10.0
  solver: fixed
  clock: external
blocks:
  Cmd: {}
  SF:
    K: '#K'
    G: '#G'
  Ref_cl: {}
  Ref_ol: {}
  Select:
    file_path: block_diagram.py
    function_name: select_cmd
    input_keys:
    - u_cl
    - u_ol
    - mode
    output_keys:
    - u
  Mode: {}
  Filter:
    file_path: block_diagram.py
    function_name: filter_first_order
    input_keys:
    - u
    - u_prev
    output_keys:
    - u_filter
  Delay:
    num_delays: 1
    initial_output: np.zeros((2,1))
  Rate:
    rising_slope: 7.906
    falling_slope: -7.906
  Luenberger:
    A: '#A'
    B: '#B'
    C: '#C'
    L: '#L'
    x0: '#x0'
  Mux:
    num_inputs: 2
  Delay_1:
    num_delays: 1
    initial_output: np.zeros((2,1))
  Camera: {}
logging:
- Cmd.outputs.out
- SF.outputs.u
- Ref_cl.outputs.out
- Ref_ol.outputs.out
- Select.outputs.u
- Mode.outputs.out
plots: []
external: parameters.py
