simulation:
  dt: 0.02
  T: 2.0
  solver: fixed
blocks:
  controller:
    K: '#K'
    G: '#G'
  step:
    value_before: [[0.0]]
    value_after: [[1.0]]
    start_time: 0.5
  system:
    A: '#A'
    B: '#B'
    C: '#C'
logging:
- controller.outputs.u
- step.outputs.out
- system.outputs.x
- system.outputs.y
plots:
- title: Ref vs Output
  signals:
  - step.outputs.out
  - system.outputs.y
- title: Command
  signals:
  - controller.outputs.u
external: parameters.py
