simulation:
  dt: 0.01
  solver: fixed
  T: 0.11
blocks:
  ramp:
    slope: 1.0
    start_time: 0
    sample_time: 0.1
  ramp_1:
    slope: 1.0
    start_time: 0
    sample_time: 0.01
logging:
- ramp.outputs.out
- ramp_1.outputs.out
plots:
- title: Rate
  signals:
  - ramp.outputs.out
  - ramp_1.outputs.out
