blocks:
- name: step
  from: sources
  type: step
  value_before: [[0]]
  value_after: [[8.0]]
  start_time: 0.4
- name: error
  from: operators
  type: sum
  num_inputs: 2
  signs: [1.0, -1.0]
- name: Kp
  from: operators
  type: gain
  gain: [[0.5]]
- name: Ki
  from: operators
  type: gain
  gain: [[0.8]]
- name: discrete_integrator
  from: operators
  type: discrete_integrator
  initial_state: [[0.0]]
- name: sum
  from: operators
  type: sum
  num_inputs: 2
- name: sofa
  from: systems
  type: sofa_plant
  scene_file: /home/aalessan/Documents/Perso/code/pySimBlocks/examples/gui/sofa/sofa_plant/finger/Finger.py
  input_keys: [cable]
  output_keys: [tip, measure]
connections:
- [step.out, error.in1]
- [error.out, Kp.in]
- [error.out, discrete_integrator.in]
- [Kp.out, sum.in1]
- [discrete_integrator.out, Ki.in]
- [Ki.out, sum.in2]
- [sum.out, sofa.cable]
- [sofa.measure, error.in2]
simulation:
  dt: 0.01
  T: 5.0
  log:
  - step.outputs.out
  - sofa.outputs.measure
  - sum.outputs.out
plot:
- title: Outputs
  log:
  - step.outputs.out
  - sofa.outputs.measure
- title: Command
  log:
  - sum.outputs.out
