# pySimBlocks - LGPL-3.0-or-later
# Copyright (c) 2026 Antoine Alessandrini

name: Product
category: operators
type: product

summary: >
  Multi-input product block.

description: >
  If "Element-wise (*)" is selected, this block computes the element-wise:
  $$
  y = u_1 operatios_1 u_2 operations_2 ... operations_m-1 u_m
  $$
  where $u_i$ are the input signals and $operations_i$ are the operations selected * or /.

  If "Matrix (@)" is selected, this block computes the matrix product:
  $$
  y = u_1 operations_1 u_2 operations_2 ... operations_m-1 u_m
  $$
  where $u_i$ are the input signals and $operations_i$ are the operations selected * (@) or / (inverse).

parameters:
  operations:
    type: str
    required: false
    autofill: true
    default: "*"
    valid: ["*", "/"]
  multiplication:
    type: enum
    required: false
    autofill: true
    default: "Element-wise (*)"
    enum: ["Element-wise (*)", "Matrix (@)"]
  sample_time:
    type: float
    required: false

ports:
  inputs:
    - name: inputs
      dynamic: true
      pattern: "in{val}"
      source:
        type: parameter
        parameter: operations
        operation: len + 1
      shape: [n, m]
      description: Input signals.

  outputs:
    - name: output
      dynamic: false
      pattern: out
      source:
        type: fixed
      shape: [n, m]
      description: Output signal.

execution:
  direct_feedthrough: true
  has_state: false
