simulation:
  dt: 0.01
  T: 5.0
  solver: fixed
blocks:
  ref:
    value_before: [[0.0]]
    value_after: [[1.0]]
    start_time: 0.5
  sum:
    signs: ++
  A:
    gain: [[0.0, 0.25], [0.3, 0.91]]
    multiplication: Matrix (K @ u)
  B:
    gain: [[0.5], [0.3]]
    multiplication: Matrix (K @ u)
  delay:
    num_delays: 1
    initial_output: [[0.0], [0.0]]
  plant:
    A: [[0.0, 0.25], [0.3, 0.91]]
    B: [[0.5], [0.3]]
    C: [[0.0, 1.0]]
    x0: [[0.0], [0.0]]
  C:
    gain: [[0.0, 1.0]]
    multiplication: Matrix (K @ u)
logging:
- ref.outputs.out
- delay.outputs.out
- plant.outputs.x
- plant.outputs.y
- C.outputs.out
plots:
- title: System response
  signals:
  - delay.outputs.out
  - plant.outputs.x
  - ref.outputs.out
