simulation:
  dt: 0.1
  solver: fixed
  T: 10.0
blocks:
  Algebraic Function:
    file_path: /home/aalessan/Documents/Perso/code/pySimBlocks/examples/generate/algebraic_function/g.py
    function_name: g
    input_keys:
    - u1
    - u2
    output_keys:
    - y1
    - y2
  Constant:
    value: [[1.0]]
  Step:
    value_before: [[0.0]]
    value_after: [[1.0]]
    start_time: 1.0
logging:
- Algebraic Function.outputs.y1
- Algebraic Function.outputs.y2
- Constant.outputs.out
- Step.outputs.out
plots: []
