blocks:
- name: pid
  from: controllers
  type: pid
  controller: PI
  Kp: [[0.5]]
  Ki: [[0.8]]
- name: step
  from: sources
  type: step
  value_before: [[0.0]]
  value_after: [[15.0]]
  start_time: 0.5
- name: error
  from: operators
  type: sum
  num_inputs: 2
  signs: [1.0, -1.0]
- name: sofa
  from: systems
  type: sofa_exchange_i_o
  input_keys: [cable]
  output_keys: [measure]
  scene_file: /home/aalessan/Documents/Perso/code/pySimBlocks/examples/gui/sofa/sofa_exchange/Finger.py
connections:
- [pid.u, sofa.cable]
- [sofa.measure, error.in2]
- [step.out, error.in1]
- [error.out, pid.e]
simulation:
  dt: 0.01
  T: 8.0
  log:
  - step.outputs.out
  - sofa.outputs.measure
  - pid.outputs.u
plot:
- title: Ref vs Measure
  log:
  - step.outputs.out
  - sofa.outputs.measure
- title: Command
  log:
  - pid.outputs.u
