blocks:
  - name: A
    from: operators
    type: gain
    gain: [[0.9, 0.4], [0.0, 0.97]]
  - name: B
    from: operators
    type: gain
    gain: [[0.0], [1.0]]
  - name: C
    from: operators
    type: gain
    gain: [[1.0, 0.0]]
  - name: delay
    from: operators
    type: delay
    num_delays: 1
    initial_output: [[0.0], [0.0]]
  - name: sum
    from: operators
    type: sum
    num_inputs: 2
    signs: [1, 1]
  - name: step
    from: sources
    type: step
    value_before: [[0]]
    value_after: [[1]]
    start_time: 0.5
  - name: plant
    from: systems
    type: linear_state_space
    A: [[0.9, 0.4], [0.0, 0.97]]
    B: [[0.0], [1.0]]
    C: [[1.0, 0.0]]
    x0: [[0.0], [0.0]]
connections:
  - [A.out, sum.in2]
  - [B.out, sum.in1]
  - [sum.out, delay.in]
  - [delay.out, A.in]
  - [delay.out, C.in]
  - [step.out, B.in]
  - [step.out, plant.u]
simulation:
  dt: 0.01
  T: 10.0
  log:
    - C.outputs.out
    - delay.outputs.out
    - step.outputs.out
    - plant.outputs.x
    - plant.outputs.y
plot:
  - title: States
    log:
      - plant.outputs.x
      - delay.outputs.out
  - title: Outputs
    log:
      - C.outputs.out
      - plant.outputs.y
  - title: Command
    log:
      - step.outputs.out
