simulation:
  dt: 0.01
  T: 5.0
  solver: fixed
blocks:
  error:
    signs: +-
  Kp:
    gain: [[0.5]]
    multiplication: Element wise (K * u)
  Ki:
    gain: [[0.8]]
    multiplication: Element wise (K * u)
  integrator:
    initial_state: [[0.0]]
    method: euler forward
  sum:
    signs: ++
  sofa:
    scene_file: ../finger/Finger.py
    input_keys:
    - cable
    output_keys:
    - tip
    - measure
    slider_params:
      ref.value:
      - -10.0
      - 50.0
      Kp.gain:
      - 0.01
      - 3.0
      Ki.gain:
      - 0.01
      - 3.0
  ref:
    value: [[1.0]]
logging:
- sum.outputs.out
- sofa.outputs.measure
- ref.outputs.out
plots:
- title: Outputs
  signals:
  - sofa.outputs.measure
  - ref.outputs.out
- title: Command
  signals:
  - sum.outputs.out
