simulation:
  dt: 0.05
  T: 10.0
  solver: fixed
blocks:
  npz:
    file_path: data.npz
    key: y
    repeat: 'False'
    use_time: 'True'
  npy:
    file_path: data.npy
    repeat: 'True'
  csv:
    file_path: data.csv
    key: y
    repeat: 'False'
    use_time: false
logging:
- npz.outputs.out
- npy.outputs.out
- csv.outputs.out
plots: []
