simulation:
  dt: 0.01
  solver: fixed
  T: 5.0
blocks:
  error:
    signs: +-
  sofa:
    scene_file: Finger.py
    input_keys:
    - cable
    output_keys:
    - tip
    - measure
    slider_params:
      ref.value:
      - -10.0
      - 50.0
      PID.Kp:
      - 0.01
      - 3.0
      PID.Ki:
      - 0.01
      - 3.0
      PID.Kd:
      - 0.001
      - 0.01
  ref:
    value: [[1.0]]
  PID:
    controller: PID
    Kp: [[0.5]]
    Ki: [[0.8]]
    Kd: [[0.005]]
    integration_method: euler forward
logging:
- sofa.outputs.measure
- ref.outputs.out
- PID.outputs.u
plots:
- title: Outputs
  signals:
  - sofa.outputs.measure
  - ref.outputs.out
- title: Command
  signals:
  - PID.outputs.u
