simulation:
  dt: 0.1
  solver: fixed
  T: 10.0
blocks:
  Step:
    value_before: 0.0
    value_after: 1.0
    start_time: 0.5
  Gain:
    gain: 1.0
  Sum:
    signs: ++
logging:
- Step.outputs.out
- Gain.outputs.out
- Sum.outputs.out
plots: []
