simulation:
  dt: 0.1
  solver: fixed
  T: 10.0
blocks:
  SofaPlant:
    scene_file: finger/Finger.py
    input_keys:
    - cable
    output_keys:
    - measure
    - tip
    slider_params:
      Constant.value:
      - 0.0
      - 50.0
  Constant:
    value: [[1.0]]
logging:
- SofaPlant.outputs.measure
- SofaPlant.outputs.tip
- Constant.outputs.out
plots:
- title: Output vs Input
  signals:
  - SofaPlant.outputs.measure
  - Constant.outputs.out
